<?php

/*
 * Copyright (C) 2009-2011 Internet Neutral Exchange Association Limited.
 * All Rights Reserved.
 * 
 * This file is part of IXP Manager.
 * 
 * IXP Manager is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, version v2.0 of the License.
 * 
 * IXP Manager is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 * 
 * You should have received a copy of the GNU General Public License v2.0
 * along with IXP Manager.  If not, see:
 * 
 * http://www.gnu.org/licenses/gpl-2.0.html
 */


/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
/**
 *
 * Auto-generated Doctrine ORM File
 *
 * @category ORM
 * @package IXP_ORM_Models
 * @copyright Copyright 2008 - 2010 Internet Neutral Exchange Association Limited <info (at) inex.ie>
 * @author Barry O'Donovan <barryo (at) inex.ie>
 */
class SwitchTable extends BaseSwitch
{


    const SWITCHTYPE_SWITCH        = 1;
    const SWITCHTYPE_CONSOLESERVER = 2;


    public static $SWITCHTYPES_TEXT = array(
        1 => 'Switch',
        2 => 'Console Server'
    );

    public function setUp()
    {
        parent::setUp();

        $this->hasOne( 'Cabinet', array( 'local' => 'cabinetid', 'foreign' => 'id') );
        $this->hasOne( 'Vendor',  array( 'local' => 'vendorid',  'foreign' => 'id') );

        $this->hasMany(
            'Switchport',  array(
                'local' => 'id',
                'foreign' => 'switchid'
                )
                );
    }
    
    
    
    public static function getDummySwitch()
    {
        $s = Doctrine_Core::getTable( 'SwitchTable' )->findOneByName( 'QuickAdd-Dummy-Switch' );
        
        if( !$s )
        {
            // get the cabinet
            $cab = Doctrine_Core::getTable( 'Cabinet' )->findOneByName( 'QuickAdd-Dummy-Cabinet' );
            
            if( !$cab )
            {
                // get the location
                $loc = Doctrine_Core::getTable( 'Location' )->findOneByName( 'QuickAdd-Dummy-Location' );
                
                if( !$loc )
                {
                    $loc = new Location();
                    $loc['name']      = 'QuickAdd-Dummy-Location';
                    $loc['shortname'] = 'qa-dummy-loc';
                    $loc->save();
                }
                
                $cab = new Cabinet();
                $cab['locationid'] = $loc['id'];
                $cab['name'] = 'QuickAdd-Dummy-Cabinet';
                $cab->save();
            }
            
            // get the vendor 
            $vendor = Doctrine_Core::getTable( 'Vendor' )->findOneByName( 'QuickAdd-Dummy-Vendor' );
                
            if( !$vendor )
            {
                $vendor = new Vendor();
                $vendor['name'] = 'QuickAdd-Dummy-Vendor';
                $vendor->save();
            }
                
            $s = new SwitchTable();
            $s['name']       = 'QuickAdd-Dummy-Switch';
            $s['cabinetid']  = $cab['id'];
            $s['switchtype'] = SwitchTable::SWITCHTYPE_SWITCH;
            $s['model']      = 'DUMMY';
            $s['vendorid']   = $vendor['id'];
            $s->save();
        }
        
        return $s;
    }

}